# This is a basic workflow to help you get started with Actions

name: AWS

env:
  SERVICE: 'AWS'
  AWS_REGION: 'us-west-2'
  AWS_INSTANCE_ID: 'i-068f876f69206b12e'
  AWS_INSTANCE_HOST: 'ec2-54-70-207-86.us-west-2.compute.amazonaws.com' 
  AWS_INSTANCE_AVAIBILITY_ZONE: 'us-west-2c' 
  AWS_INSTANCE_USER: 'ubuntu'  

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: 'Tag to deploy'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Set Environment Variables
      run: |
        echo "::set-env name=REGION::${{env.SERVICE}}_REGION"
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env[env.REGION] }}

    - name: Check AWS CLI version
      run: |
        aws --version
        echo ${{ env[env.REGION] }}

    - name: Generate temp key
      run: |
        aws ssm send-command \
          --instance-ids "i-0ac9fcaa2acbaf1f9" \
          --document-name "AWS-RunShellScript" \
          --parameters workingDirectory="/home/ec2-user",\
            commands=["touch test3.txt",\
              "touch test4.txt"]
