# This is a basic workflow to help you get started with Actions

name: AWS

env:
  SERVICE: 'AWS'
  REGION: ${{env.SERVIVE}}_REGION   
  AWS_REGION: 'us-west-2'
  AWS_INSTANCE_ID: 'i-068f876f69206b12e'
  AWS_INSTANCE_HOST: 'ec2-54-70-207-86.us-west-2.compute.amazonaws.com' 
  AWS_INSTANCE_AVAIBILITY_ZONE: 'us-west-2c' 
  AWS_INSTANCE_USER: 'ubuntu'  

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: 'Tag to deploy'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env[env.SERVICE.'_REGION'] }}

    - name: Check AWS CLI version
      run: |
        aws --version
        echo ${{ env[env.REGION] }}

    - name: Generate temp key
      run: |
        cd ~
        ssh-keygen -t rsa -b 4096 -N "" -C "temporary-key" -f ec2temp 
        pwd
        ls
    
    - name: Add temp key to instance
      run: |
        cd ~
        aws ec2-instance-connect send-ssh-public-key \
          --instance-id ${{ env.AWS_INSTANCE_ID }} \
          --instance-os-user ${{ env.AWS_INSTANCE_USER }} \
          --availability-zone ${{ env.AWS_INSTANCE_AVAIBILITY_ZONE }} \
          --ssh-public-key file://ec2temp.pub

    - name: Connect to instance
      run: |
        echo "Tag: tags/${{ github.event.inputs.tag }}"
        cd ~
        ssh -i "ec2temp" -o StrictHostKeyChecking=no -T \
          ${{ env.AWS_INSTANCE_USER }}@${{ env.AWS_INSTANCE_HOST }} \
            "cd /var/www/html/; \
            sudo git checkout .; \
            sudo git fetch; \
            sudo git checkout tags/${{ github.event.inputs.tag }}"
